export {
  BLOCK_TYPES,
  BLOCK_CATALOG,
  blockTypeSchema,
  getBlockDefinition,
  isBlockType,
  PRIMARY_ACTION_BLOCK_TYPES,
  isPrimaryActionBlockType,
  type PrimaryActionBlockType,
  type BlockDefinition,
  type BlockType,
  // Esquema y tipo por bloque — el render público (F2.7) y, más adelante, el constructor (F2.9)
  // necesitan la forma exacta de cada `config`, no `unknown`.
  profileSchema,
  heroSchema,
  textSchema,
  linkSchema,
  socialSchema,
  imageBlockSchema,
  gallerySchema,
  bookingBlockSchema,
  catalogBlockSchema,
  videoSchema,
  whatsappSchema,
  contactActionsSchema,
  contactFormSchema,
  serviceSchema,
  dividerSchema,
  faqSchema,
  testimonialsSchema,
  countdownSchema,
  pricingSchema,
  pricingPlanSchema,
  PRICING_PERIODS,
  mapSchema,
  musicSchema,
  eventsSchema,
  eventItemSchema,
  newsletterBlockSchema,
  type ProfileBlockConfig,
  type HeroBlockConfig,
  type TextBlockConfig,
  type LinkBlockConfig,
  type SocialBlockConfig,
  type ImageBlockConfig,
  type GalleryBlockConfig,
  type VideoBlockConfig,
  type WhatsappBlockConfig,
  type ContactActionsBlockConfig,
  type ContactFormBlockConfig,
  type ServiceBlockConfig,
  type DividerBlockConfig,
  type FaqBlockConfig,
  type BookingBlockConfig,
  type CatalogBlockConfig,
  type TestimonialsBlockConfig,
  type CountdownBlockConfig,
  type PricingBlockConfig,
  type PricingPlan,
  type MapBlockConfig,
  type MusicBlockConfig,
  type EventsBlockConfig,
  type EventItem,
  type NewsletterBlockConfig,
} from "./catalog.js";
export { parseStoredBlock, type StoredBlockResult } from "./stored-block.js";
export { collectRichTextPaths } from "./rich-text-paths.js";
export {
  RICH_TEXT_ALLOWED_TAGS,
  RICH_TEXT_LINK_ATTRIBUTES,
  RICH_TEXT_ALLOWED_SCHEMES,
} from "./rich-text-policy.js";
export {
  IMAGE_ALT_REQUIRED_MESSAGE,
  findImagesWithoutAlt,
  SOCIAL_NETWORKS,
  SOCIAL_NETWORK_LABELS,
  detectSocialNetwork,
  type SocialNetwork,
  VIDEO_PROVIDERS,
  parseVideoUrl,
  safeUrlSchema,
  socialNetworkSchema,
  phoneSchema,
  type VideoProvider,
} from "./primitives.js";
export {
  MUSIC_PROVIDERS,
  MUSIC_PROVIDER_LABELS,
  musicEmbedHeight,
  musicEmbedSrc,
  musicPublicUrl,
  parseMusicUrl,
  storedMusicSchema,
  type MusicProvider,
  type StoredMusic,
} from "./music.js";
export {
  SITE_TIME_ZONES,
  formatLocalDateTime,
  localDateTimeSchema,
  localDateTimeToInstant,
  timeZoneSchema,
} from "./time.js";
